'use client';

import { m, AnimatePresence, useReducedMotion } from 'framer-motion';
import { Database, Send, Cpu, HardDrive, LineChart } from 'lucide-react';
import { useState } from 'react';

const NODES = [
  { id: 'sources', label: 'Sources', icon: Send, color: 'text-zinc-400', tech: 'APIs, Databases, Logs', desc: 'Raw events generated by applications.' },
  { id: 'ingestion', label: 'Ingestion', icon: Database, color: 'text-blue-400', tech: 'Kafka, Fivetran, Airbyte', desc: 'Buffering and extracting raw data reliably.' },
  { id: 'transformation', label: 'Transformation', icon: Cpu, color: 'text-purple-400', tech: 'Spark, dbt, Flink', desc: 'Cleaning, joining, and shaping data into models.' },
  { id: 'storage', label: 'Storage', icon: HardDrive, color: 'text-emerald-400', tech: 'Snowflake, S3, Iceberg', desc: 'Persisting data in analytical formats (Parquet/Columnar).' },
  { id: 'analytics', label: 'Analytics', icon: LineChart, color: 'text-orange-400', tech: 'Tableau, Looker, Hex', desc: 'Dashboards, reporting, and Machine Learning.' },
];

export function DataJourney() {
  const [hoveredNode, setHoveredNode] = useState<string | null>(null);
  const shouldReduceMotion = useReducedMotion();

  return (
    <section id="learn" className="w-full py-16 md:py-24 px-6 border-t border-zinc-900 bg-zinc-950/30 relative scroll-mt-24">
      <div className="container mx-auto flex flex-col items-center">
        
        <div className="text-center mb-24 max-w-2xl">
          <h2 className="text-3xl md:text-5xl font-bold mb-4 tracking-tight">See the Data Engineering Journey</h2>
          <p className="text-zinc-400 text-lg">From raw events to analytics-ready data.</p>
        </div>

        <div className="w-full max-w-6xl relative h-64 flex items-center justify-between font-mono text-xs">
          
          {/* Background Track Line */}
          <div className="absolute left-10 right-10 h-0.5 bg-zinc-800 top-1/2 -translate-y-1/2" />
          
          {/* Animated data packet on the track */}
          <div className="absolute left-10 right-10 h-10 top-1/2 -translate-y-1/2 pointer-events-none flex items-center overflow-hidden">
             {!shouldReduceMotion && (
               <m.div 
                  animate={{ x: ['0%', '100%'] }} 
                  transition={{ duration: 5, repeat: Infinity, ease: 'linear' }} 
                  className="w-16 h-1 bg-gradient-to-r from-transparent via-blue-500 to-transparent shadow-[0_0_15px_rgba(59,130,246,0.8)]"
               />
             )}
          </div>

          {NODES.map((node, i) => {
            const isHovered = hoveredNode === node.id;
            const isDimmed = hoveredNode !== null && !isHovered;

            return (
              <div 
                key={node.id}
                className="relative z-10 flex flex-col items-center group cursor-pointer"
                onMouseEnter={() => setHoveredNode(node.id)}
                onMouseLeave={() => setHoveredNode(null)}
              >
                <div className={`w-20 h-20 rounded-2xl bg-black border-2 transition-all duration-300 flex items-center justify-center
                  ${isHovered ? 'border-zinc-300 scale-110 shadow-[0_0_30px_rgba(255,255,255,0.1)]' : 'border-zinc-800'}
                  ${isDimmed ? 'opacity-30' : 'opacity-100'}
                `}>
                  <node.icon className={`w-8 h-8 ${isHovered ? 'text-white' : node.color} transition-colors`} />
                </div>
                
                <div className={`mt-6 text-center transition-all duration-300 ${isDimmed ? 'opacity-30' : 'opacity-100'}`}>
                  <div className="font-bold text-sm text-zinc-300 mb-1">{node.label}</div>
                </div>

                {/* Hover Popover */}
                <AnimatePresence>
                  {isHovered && (
                    <m.div 
                      initial={{ opacity: 0, y: 10, scale: 0.95 }}
                      animate={{ opacity: 1, y: 0, scale: 1 }}
                      exit={{ opacity: 0, y: 10, scale: 0.95 }}
                      className="absolute top-32 w-56 bg-zinc-900 border border-zinc-700 p-4 rounded-xl shadow-2xl pointer-events-none"
                    >
                      <div className="font-bold text-blue-400 mb-2">{node.tech}</div>
                      <div className="text-zinc-400 mb-4">{node.desc}</div>
                      <div className="text-[10px] text-zinc-500 font-bold">HOVER TO LEARN MORE</div>
                    </m.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })}

        </div>
      </div>
    </section>
  );
}
